name: Push to Daily Blog

on: push

jobs:
  update-metamageia-vault-quartz:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes blog content folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: './metamageia/post/'
        destination_repo: 'metamageia/blog.gagelara'
        destination_folder: 'content/post/'
        destination_branch: 'main'
        user_email: 'metamageia@gmail.com'
        user_name: 'metamageia'
        commit_msg: 'Update the blog.gagelara Hugo Website Content'